CREATE TABLE [dbo].[Struktura] (
    [RelacjaId]            INT             NOT NULL,
    [StrukturaObiektId]    INT             NOT NULL,
    [IsMain]               BIT             CONSTRAINT [DF_Struktura_IsMain] DEFAULT ((0)) NOT NULL,
    [IsStatus]             BIT             CONSTRAINT [DF_Struktura_IsStatus_1] DEFAULT ((0)) NOT NULL,
    [StatusS]              INT SPARSE      NULL,
    [StatusSFrom]          DATETIME SPARSE NULL,
    [StatusSTo]            DATETIME SPARSE NULL,
    [StatusSFromBy]        INT SPARSE      NULL,
    [StatusSToBy]          INT SPARSE      NULL,
    [StatusW]              INT SPARSE      NULL,
    [StatusWFrom]          DATETIME SPARSE NULL,
    [StatusWTo]            DATETIME SPARSE NULL,
    [StatusWFromBy]        INT SPARSE      NULL,
    [StatusWToBy]          INT SPARSE      NULL,
    [StatusP]              INT SPARSE      NULL,
    [StatusPFrom]          DATETIME SPARSE NULL,
    [StatusPTo]            DATETIME SPARSE NULL,
    [StatusPFromBy]        INT SPARSE      NULL,
    [StatusPToBy]          INT SPARSE      NULL,
    [ObowiazujeOd]         DATETIME        NULL,
    [ObowiazujeDo]         DATETIME SPARSE NULL,
    [IsValid]              BIT             CONSTRAINT [DF_Struktura_IsValid_1] DEFAULT ((1)) NULL,
    [ValidFrom]            DATETIME        CONSTRAINT [DF_Struktura_ValidFrom_1] DEFAULT (getdate()) NOT NULL,
    [ValidTo]              DATETIME SPARSE NULL,
    [IsDeleted]            BIT             CONSTRAINT [DF_Struktura_IsDeleted_1] DEFAULT ((0)) NOT NULL,
    [DeletedFrom]          DATETIME SPARSE NULL,
    [DeletedBy]            INT SPARSE      NULL,
    [CreatedOn]            DATETIME        CONSTRAINT [DF_Struktura_CreatedOn_1] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]            INT             NULL,
    [LastModifiedOn]       DATETIME SPARSE NULL,
    [LastModifiedBy]       INT SPARSE      NULL,
    [IsAlternativeHistory] BIT             DEFAULT ((0)) NULL,
    [IsMainHistFlow]       BIT             DEFAULT ((0)) NULL,
    [RealCreatedOn]        DATETIME        DEFAULT (getdate()) NOT NULL,
    [RealLastModifiedOn]   DATETIME SPARSE NULL,
    [RealDeletedFrom]      DATETIME SPARSE NULL,
    [StrukturaLinkId]      INT             NULL,
    CONSTRAINT [PK_Struktura] PRIMARY KEY CLUSTERED ([RelacjaId] ASC, [StrukturaObiektId] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_Struktura_Relacje] FOREIGN KEY ([RelacjaId]) REFERENCES [dbo].[Relacje] ([Id]),
    CONSTRAINT [FK_Struktura_Struktura_Obiekt1] FOREIGN KEY ([StrukturaObiektId]) REFERENCES [dbo].[Struktura_Obiekt] ([Id])
);

