CREATE TABLE [dbo].[TypObiektu_Relacje_Cechy] (
    [TableID]              INT      NULL,
    [TypObiektuID]         INT      NOT NULL,
    [RelacjaID]            INT      NOT NULL,
    [CechaId]              INT      NOT NULL,
    [PolaczenieID]         INT      NOT NULL,
    [IsValid]              BIT      CONSTRAINT [DF_ObiektyCechyRelacje_IsValid] DEFAULT ((1)) NULL,
    [ValidFrom]            DATETIME CONSTRAINT [DF_ObiektyCechyRelacje_ValidFrom] DEFAULT (getdate()) NOT NULL,
    [ValidTo]              DATETIME NULL,
    [IsAlternativeHistory] BIT      DEFAULT ((0)) NULL,
    [IsMainHistFlow]       BIT      DEFAULT ((0)) NULL,
    [ZmianaOd]             DATETIME NULL,
    [ZmianaDo]             DATETIME NULL,
    [ObowiazujeOd]         DATETIME NULL,
    [ObowiazujeDo]         DATETIME NULL,
    [IsDeleted]            BIT      DEFAULT ((0)) NOT NULL,
    [DeletedFrom]          DATETIME NULL,
    [DeletedBy]            INT      NULL,
    [CreatedOn]            DATETIME DEFAULT (getdate()) NOT NULL,
    [CreatedBy]            INT      NULL,
    [LastModifiedOn]       DATETIME NULL,
    [LastModifiedBy]       INT      NULL,
    [RealCreatedOn]        DATETIME DEFAULT (getdate()) NOT NULL,
    [RealLastModifiedOn]   DATETIME NULL,
    [RealDeletedFrom]      DATETIME NULL,
    [RealArchivedFrom]     DATETIME NULL,
    FOREIGN KEY ([RelacjaID]) REFERENCES [dbo].[Relacje] ([Id]),
    CONSTRAINT [FK_TypObiektu_Relacje_Cechy_Cecha] FOREIGN KEY ([CechaId]) REFERENCES [dbo].[Cechy] ([Cecha_ID]),
    CONSTRAINT [FK_TypObiektu_Relacje_Cechy_Relacja] FOREIGN KEY ([RelacjaID]) REFERENCES [dbo].[Relacje] ([Id]),
    CONSTRAINT [FK_TypObiektu_Relacje_Cechy_TypObiektu] FOREIGN KEY ([TypObiektuID]) REFERENCES [dbo].[TypObiektu] ([TypObiekt_ID])
);

